name: 🐛 Bug report
description: Something isn't working as expected
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: When I do X, Y happens instead of Z.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "OS, browser, version…"
    validations:
      required: false
